# Starting Image
FROM node:22-bullseye-slim
ENV POSTGRESQL_PASS micare_chat2024!
ENV POSTGRES_HOST postgres
ENV POSTGRES_PORT 5432
ENV POSTGRES_DB micare_chat
ENV POSTGRES_USER postgres
ENV MICARE_CHAT_OUTSIDEPORT 3001
ENV LLM_API http://149.132.176.54:5000/askLLM
# Set the working directory in the container
WORKDIR /app
# Copy the application package and lock
COPY . /app
# Install app dependencies using PNPM
RUN npm install -g pnpm
# Run pnpm install
RUN pnpm install
# Create build
RUN pnpm build
#Add .env
#COPY .env /app/.env
# Expose the app
EXPOSE 3000
# Start the application
CMD ["pnpm", "start"]