import "~/styles/globals.css";

import { TRPCReactProvider } from "~/trpc/react";
import { MicareSidebarProvider } from "~/app/components/sidebar/sidebar-provider";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Micare Chat",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="h-screen overflow-hidden">
        <TRPCReactProvider>
          <MicareSidebarProvider>{children}</MicareSidebarProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
